
name: frontend
description: A new Flutter project for warehouse management.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # For Navigation
  go_router: ^13.2.0

  # For Camera and ML
  camera: ^0.10.5+9
  tflite_flutter: ^0.10.4
  image_picker: ^1.0.7 # Kept for potential gallery access
  image: ^4.1.7         # For image processing

  # For Permissions
  permission_handler: ^11.3.0

  # For Networking
  http: ^1.1.0
  
  # For State Management
  provider: ^6.1.1
  
  # For Local Storage
  shared_preferences: ^2.2.2
  
  # For UI and utility
  intl: ^0.18.1
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/models/labels.txt
    - assets/models/mobilenet.tflite
